package com.ticklog.core.pdf

import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import com.ticklog.domain.model.ChecklistStatistics
import com.ticklog.domain.model.DailyChecklist
import com.ticklog.domain.model.DateFormat
import com.ticklog.domain.model.ReportData
import java.io.OutputStream
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.time.format.FormatStyle
import javax.inject.Inject
import kotlin.math.roundToInt

/**
 * Renders a [ReportData] into a professional, black-and-white A4 PDF using the
 * platform [PdfDocument] — no third-party libraries.
 *
 * The layout is a flowing document: a title + summary block, then one section
 * per day. A small paginator tracks the vertical cursor and starts a new page
 * (drawing the running header and footer, with page numbers) whenever the next
 * line would cross the bottom margin, so tables never overlap and content never
 * runs off the page. All text is word-wrapped to the content width.
 */
class PdfReportRenderer @Inject constructor() {

    /**
     * Renders [data] to [output] using [dateFormat] for dates. The stream is not
     * closed here (the caller owns it).
     */
    fun render(data: ReportData, dateFormat: DateFormat, output: OutputStream) {
        val document = PdfDocument()
        Session(document, data, dateFormat).run()
        document.writeTo(output)
        document.close()
    }

    /** Mutable rendering state for a single document. */
    private class Session(
        private val document: PdfDocument,
        private val data: ReportData,
        dateFormat: DateFormat,
    ) {
        private val dateFormatter: DateTimeFormatter =
            dateFormat.pattern?.let(DateTimeFormatter::ofPattern)
                ?: DateTimeFormatter.ofLocalizedDate(FormatStyle.MEDIUM)
        private val dateTimeFormatter: DateTimeFormatter =
            DateTimeFormatter.ofPattern("d MMM yyyy, HH:mm")

        private lateinit var page: PdfDocument.Page
        private lateinit var canvas: Canvas
        private var y = 0f
        private var pageNumber = 0

        // Paints (points == pixels at the 72dpi page scale).
        private val title = paint(20f, bold = true)
        private val heading = paint(13f, bold = true)
        private val dayHeading = paint(12f, bold = true)
        private val body = paint(10f)
        private val label = paint(9f, bold = true, color = GRAY)
        private val secondary = paint(9f, color = GRAY)
        private val note = paint(9f, color = GRAY, italic = true)
        private val footer = paint(8f, color = GRAY)
        private val brand = paint(11f, bold = true)
        private val rule = Paint().apply { color = LINE; strokeWidth = 0.7f }
        private val faintRule = Paint().apply { color = FAINT_LINE; strokeWidth = 0.6f }

        fun run() {
            startPage()
            drawTitleBlock()
            drawSummary()
            if (data.days.isEmpty()) {
                drawLines("No entries in this period.", secondary, CONTENT_LEFT, CONTENT_WIDTH)
            } else {
                data.days.forEach(::drawDay)
            }
            document.finishPage(page)
        }

        // --- Page lifecycle -------------------------------------------------

        private fun startPage() {
            pageNumber++
            val info = PdfDocument.PageInfo
                .Builder(PAGE_WIDTH.toInt(), PAGE_HEIGHT.toInt(), pageNumber)
                .create()
            page = document.startPage(info)
            canvas = page.canvas
            drawRunningHeader()
            drawRunningFooter()
            y = CONTENT_TOP
        }

        private fun ensureSpace(needed: Float) {
            if (y + needed > CONTENT_BOTTOM) {
                document.finishPage(page)
                startPage()
            }
        }

        private fun drawRunningHeader() {
            canvas.drawText("TickLog", CONTENT_LEFT, MARGIN + 12f, brand)
            val rangeLabel = rangeLabel()
            if (rangeLabel.isNotEmpty()) {
                canvas.drawText(
                    rangeLabel,
                    CONTENT_RIGHT - footer.measureText(rangeLabel),
                    MARGIN + 12f,
                    footer,
                )
            }
            val lineY = MARGIN + HEADER_HEIGHT - 6f
            canvas.drawLine(CONTENT_LEFT, lineY, CONTENT_RIGHT, lineY, rule)
        }

        private fun drawRunningFooter() {
            val baseline = PAGE_HEIGHT - MARGIN - 4f
            canvas.drawLine(CONTENT_LEFT, baseline - 14f, CONTENT_RIGHT, baseline - 14f, rule)
            canvas.drawText("Generated by TickLog", CONTENT_LEFT, baseline, footer)
            val pageLabel = "Page $pageNumber"
            canvas.drawText(pageLabel, CONTENT_RIGHT - footer.measureText(pageLabel), baseline, footer)
        }

        // --- Content blocks -------------------------------------------------

        private fun drawTitleBlock() {
            drawLines("Checklist Report", title, CONTENT_LEFT, CONTENT_WIDTH)
            space(6f)
            drawLines("Generated: ${data.generatedAt.format(dateTimeFormatter)}", secondary, CONTENT_LEFT, CONTENT_WIDTH)
            val rangeLabel = rangeLabel()
            if (rangeLabel.isNotEmpty()) {
                drawLines("Period: $rangeLabel", secondary, CONTENT_LEFT, CONTENT_WIDTH)
            }
            drawLines("Generated by TickLog", secondary, CONTENT_LEFT, CONTENT_WIDTH)
            space(6f)
            divider()
        }

        private fun drawSummary() {
            drawLines("Summary", heading, CONTENT_LEFT, CONTENT_WIDTH)
            space(4f)
            val stats: ChecklistStatistics = data.statistics
            keyValue("Overall completion", percent(stats.overallCompletionRate))
            keyValue("Average completion", percent(stats.averageDailyCompletion))
            keyValue("Current streak", "${stats.currentStreak} days")
            keyValue("Longest streak", "${stats.longestStreak} days")
            keyValue("Tasks completed", stats.totalCompletedTasks.toString())
            keyValue("Tasks skipped", stats.totalIncompleteTasks.toString())
            keyValue("Checklist days", stats.totalChecklistDays.toString())
            space(4f)
            divider()
        }

        private fun drawDay(day: DailyChecklist) {
            ensureSpace(dayHeading.fontSpacing + body.fontSpacing)
            drawLines(day.date.format(dateFormatter), dayHeading, CONTENT_LEFT, CONTENT_WIDTH)
            val summary = "${percent(day.completionRate)} • ${day.completedCount} of ${day.totalCount} completed"
            drawLines(summary, secondary, CONTENT_LEFT, CONTENT_WIDTH)
            space(2f)

            val completed = day.tasks.filter { it.isCompleted }
            val incomplete = day.tasks.filter { !it.isCompleted }

            if (completed.isNotEmpty()) {
                drawLines("Completed", label, CONTENT_LEFT, CONTENT_WIDTH)
                completed.forEach(::drawTask)
            }
            if (incomplete.isNotEmpty()) {
                drawLines("Incomplete", label, CONTENT_LEFT, CONTENT_WIDTH)
                incomplete.forEach(::drawTask)
            }
            space(6f)
            divider()
        }

        private fun drawTask(task: com.ticklog.domain.model.DailyTask) {
            drawLines("•  ${task.title}", body, CONTENT_LEFT + BULLET_INDENT, CONTENT_WIDTH - BULLET_INDENT)
            val taskNote = task.note
            if (!taskNote.isNullOrBlank()) {
                drawLines(taskNote, note, CONTENT_LEFT + NOTE_INDENT, CONTENT_WIDTH - NOTE_INDENT)
            }
        }

        // --- Primitives -----------------------------------------------------

        /** Draws word-wrapped [text], advancing the cursor and breaking pages. */
        private fun drawLines(text: String, paint: Paint, x: Float, maxWidth: Float) {
            for (line in wrap(text, paint, maxWidth)) {
                ensureSpace(paint.fontSpacing)
                canvas.drawText(line, x, y - paint.ascent(), paint)
                y += paint.fontSpacing
            }
        }

        private fun keyValue(key: String, value: String) {
            ensureSpace(body.fontSpacing)
            canvas.drawText(key, CONTENT_LEFT, y - body.ascent(), secondary)
            canvas.drawText(value, CONTENT_RIGHT - body.measureText(value), y - body.ascent(), body)
            y += body.fontSpacing
        }

        private fun divider() {
            ensureSpace(8f)
            canvas.drawLine(CONTENT_LEFT, y + 3f, CONTENT_RIGHT, y + 3f, faintRule)
            y += 8f
        }

        private fun space(height: Float) {
            y += height
        }

        private fun rangeLabel(): String {
            val start = data.rangeStart ?: return ""
            val end = data.rangeEnd ?: return ""
            return if (start == end) {
                start.format(dateFormatter)
            } else {
                "${start.format(dateFormatter)} – ${end.format(dateFormatter)}"
            }
        }

        private fun percent(rate: Float): String = "${(rate * 100).roundToInt()}%"

        /** Greedy word-wrap to [maxWidth], hard-breaking words that are too long. */
        private fun wrap(text: String, paint: Paint, maxWidth: Float): List<String> {
            if (text.isEmpty()) return listOf("")
            val lines = mutableListOf<String>()
            var current = StringBuilder()
            for (word in text.split(" ")) {
                val candidate = if (current.isEmpty()) word else "$current $word"
                when {
                    paint.measureText(candidate) <= maxWidth -> current = StringBuilder(candidate)
                    paint.measureText(word) > maxWidth -> {
                        if (current.isNotEmpty()) { lines.add(current.toString()); current = StringBuilder() }
                        for (ch in word) {
                            if (current.isNotEmpty() && paint.measureText("$current$ch") > maxWidth) {
                                lines.add(current.toString())
                                current = StringBuilder()
                            }
                            current.append(ch)
                        }
                    }
                    else -> {
                        if (current.isNotEmpty()) lines.add(current.toString())
                        current = StringBuilder(word)
                    }
                }
            }
            if (current.isNotEmpty()) lines.add(current.toString())
            return lines
        }

        private fun paint(size: Float, bold: Boolean = false, italic: Boolean = false, color: Int = Color.BLACK): Paint {
            val style = when {
                bold && italic -> Typeface.BOLD_ITALIC
                bold -> Typeface.BOLD
                italic -> Typeface.ITALIC
                else -> Typeface.NORMAL
            }
            return Paint().apply {
                isAntiAlias = true
                textSize = size
                this.color = color
                typeface = Typeface.create(Typeface.SANS_SERIF, style)
            }
        }
    }
}

// A4 at 72dpi, in points. File-level so the nested Session class sees them.
private const val PAGE_WIDTH = 595f
private const val PAGE_HEIGHT = 842f
private const val MARGIN = 42f
private const val HEADER_HEIGHT = 34f
private const val FOOTER_HEIGHT = 28f

private const val CONTENT_LEFT = MARGIN
private const val CONTENT_RIGHT = PAGE_WIDTH - MARGIN
private const val CONTENT_WIDTH = CONTENT_RIGHT - CONTENT_LEFT
private const val CONTENT_TOP = MARGIN + HEADER_HEIGHT
private const val CONTENT_BOTTOM = PAGE_HEIGHT - MARGIN - FOOTER_HEIGHT

private const val BULLET_INDENT = 10f
private const val NOTE_INDENT = 22f

private val GRAY = Color.rgb(90, 90, 90)
private val LINE = Color.rgb(150, 150, 150)
private val FAINT_LINE = Color.rgb(210, 210, 210)
